### ISSUE TITLE
Write Non-functional Requirements

### ISSUE THREAD

**Issue by semihYILMAZ37** [bounswe/bounswe2024group5#279]

**Comment by semihYILMAZ37** [comment]
I added non-functional requirements to [requirements page](https://github.com/bounswe/bounswe2024group5/wiki/Requirements). @HutkuC could you please review them?

**Comment by HutkuC** [comment]
@semihYILMAZ37
I think we might be not able to handle some of the requirements since this is a school project and we do not have that much time. For example requirement 2.2.2, we will not have time to test it. Or 2.3.1, we are not buying a domain or setting up an email service, so there will not be a business email.
However, all of the requirements are good and essential for such an application in real life. If we are still okay to keep them with knowing that we will not meet some requirements, we can close the issue.
