### ISSUE TITLE
Write User scenarios

### ISSUE THREAD

**Issue by ramazanoacar** [bounswe/bounswe2024group5#282]
## Description
The issue description.

## Tasks
- [x] Write total of 4 user scenarios 

## Estimated Time
Time estimation in minutes.

## Deadline
Date(08/10/2024) - 23:00

## Reviewer
@arincdemir - Deadline of the review(10/10/2024 - 23:00)

**Comment by ramazanoacar** [comment]
I and Utku agreed on that we both write 2 scenarios per person

**Comment by ramazanoacar** [comment]
I finished 2 scenarios.
[first one](https://github.com/bounswe/bounswe2024group5/wiki/User-Scenario-2-%E2%80%90-Find-Quiz-from-the-Forum)
[second one](https://github.com/bounswe/bounswe2024group5/wiki/User-Scenario-3-%E2%80%90-Ask-Question-in-the-Forum)

After @HutkuC finishes his second scenario, this issue is ready for review.

**Comment by HutkuC** [comment]
[User Scenario 1](https://github.com/bounswe/bounswe2024group5/wiki/User-Scenario-1-%E2%80%90-Quiz-Generation)
[User Scenario 4](https://github.com/bounswe/bounswe2024group5/wiki/User-Scenario-2-%E2%80%90-Find-Quiz-from-the-Forum)
4 user scenarios are written. The issue is ready for review. @arincdemir
