### ISSUE TITLE
Design Class Diagram

### ISSUE THREAD

**Issue by semihYILMAZ37** [bounswe/bounswe2024group5#307]
## Description
UML Class diagram must be designed.

## Tasks
- [x] class diagram designed.

## Estimated Time
5h

## Deadline
18/10/2024 - 23:59

## Reviewer
@HutkuC  , @set120120 - Deadline of the review(20/10/2024 - 23:59)

**Comment by semihYILMAZ37** [comment]
initial version of  [class diagram](https://github.com/bounswe/bounswe2024group5/wiki/Class-Diagram) is ready.

**Comment by set120120** [comment]
I think in User table we should use "elo" or "elo points" instead of "points". 
There should be also a "elo point" in Quiz table.
I think we should keep the wrong answers in a different List in QuizAttempt table.

These are the things I noticed for now. I will check again and write down what I think needs to be changed.

**Comment by semihYILMAZ37** [comment]
I revised the class diagram. @set120120 and @HutkuC it is ready for your reviews.

**Comment by set120120** [comment]
Thank you for your hard work @semihYILMAZ37 . Now, I am closing the issue.
