### ISSUE TITLE
UML Use Case Diagram

### ISSUE THREAD

**Issue by set120120** [bounswe/bounswe2024group5#308]
## Description
Use Case Diagram should be drawn.

## Tasks
- [x] Create Use Case Diagram

## Estimated Time
5 hours

## Deadline
19.10.2024 - 23.59 

## Reviewer
@ebrarkiziloglu  - Deadline of the review(dd/mm/yyyy - hour)

**Comment by set120120** [comment]
The first version of the UML Use Case Diagram is ready thanks to the efforts of me, @arincdemir and @ramazanoacar . Now we are waiting for your feedback @ebrarkiziloglu . Changes will be made according to your feedback.

**Comment by set120120** [comment]
The link of [UML Use Case Diagram](https://drive.google.com/file/d/1M_b6aqOspNbgBsxRpxisJ3zOlWB1eqAZ/view?usp=sharing)

**Comment by arincdemir** [comment]
1. I added `extends `to those since the profile details probably have submenus, and its possible for the user to see some of them while not seeing others.
2. I added a `Choose question type` use-case. I connected the question types using the `generalization` relationship instead of the `include` since they include and cover all the cases.
3. I deleted the "add tags" use-case because we didnt talk about that in the requirements.
4. Good idea! I added a new `Add Question` use-case and connected the `Create Question` and `Add Favorited Question` with `generalization`
5.  Good idea! I added `Edit Title`, `Edit Questions`, `Edit Description` and `Edit Picture` with `extends`.
6.  I added `Add title to a post`, `Add Tags to a post`, `Add Body to a post` with `include`.
7. I modified it as you said.

Also, some of the `include` and `extends` were created without the straight and dotted line, I changed them. I think they should be straight and dotted because of the UML conventions.

I also changed the stuff under `Change Profile Details` from `generalization` to `extends` since the user can do multiple of them at once. Generalization is for choosing one and only one of them.

Thank you for your review @ebrarkiziloglu. You noticed a lot of important stuff!

**Comment by ebrarkiziloglu** [comment]
@arincdemir, thanks for the great changes!

For the 2. point, should `Pick Question Word` be connected to `Create Question` with the current `include` connection, instead of being connected to `Choose Question Type`?

For the 7. point, Thank you for adding the use-case. I think `See Forum Page` should also directly `include` the `See specific post` use-case, since it is possible to view specific posts from the feed without searching for anything. At least this was what I imagined.

**Comment by arincdemir** [comment]
I fixed the 2. point.
You are right, searching for posts should not be a prerequisite for seeing posts. I fixed it.
Thank you.

**Comment by set120120** [comment]
For the 7. point, you are right, because it is possible to see posts from the feed without searching. I changed it to "include" from "extends".
Thank you.

**Comment by ebrarkiziloglu** [comment]
LGTM!! Thanks for you efforts everyone, closing the issue now.
